const paletteMap = {
  default: ['Normal', '#fffdc9'],
  theme_thanksgiving: ['Thanksgiving', '#f5e9ce'],
  halloween: ['Halloween', '#444444'],
  theme_cga: ['CGA', '#ffff55'],
  shades_of_grey: ['Grayscale', '#e9e9e9'],
  theme_bw: ['Black and white', '#ffffff'],
  theme_gameboy: ['Gameboy', '#9bbc0f'],
  theme_neon: ['Neon', '#00abff'],
  theme_sepia: ['Sepia', '#ffe2c4'],
  theme_valentines: ["Valentine's", '#ffccdf'],
  theme_blues: ['the blues', '#295c6f'],
  theme_spring: ['Spring', '#ffffff'],
  theme_beach: ['Beach', '#f7dca2'],
  theme_beach_2: ['Tide Pool', '#2271a2'],
  theme_coty_2016: ['Colors of 2016', '#648589'],
  theme_bee: ['Bee', '#ffffff'],
  theme_coty_2017: ['Colors of 2017', '#5f7278'],
  theme_fire_ice: ['Fire and Ice', '#040526'],
  theme_coty_2018: ['Canyon Sunset', '#2e1b50'],
  theme_juice: ['Juice', '#fced95'],
  theme_tropical: ['Tropical', '#2f0946'],
  theme_grimby_grays: ['Grimby Grays', '#f0efeb'],
  theme_fury_road: ['Fury Road', '#893f1d'],
  theme_candy: ['Candy', '#793abd'],
  theme_holiday_2: ['Holiday', '#f6f6f6'],
  theme_blues_2: ['Blues', '#0f1328'],
  theme_sin_city: ['Sin City', '#000000'],
  theme_lucky_clover: ['Lucky Clover', '#0c442c'],
  theme_drawception: ["D's Exclusive", '#0ee446'],
  theme_retina_burn: ['Retina Burn', '#ff0b11'],
  theme_easter: ['Easter', '#ddf7a8'],
  theme_neapolitan: ['Neapolitan', '#fff7e1'],
  theme_lemonade: ['Lemonade', '#ffebaa'],
  theme_school_pen: ['School Pen', '#fbfcfd'],
  theme_dimmed: ['Dimmed', '#1c0b11'],
  theme_treasure: ['Treasure', '#412a23'],
  theme_witches_brew: ['Witches Brew', '#100b16']
}

export default paletteMap
